const express=require('express');
const db=require('../config/db');
const {createReportPdf,rupiah,date,COLORS}=require('../services/reportPdf');
const router=express.Router();
function invNo(){const d=new Date();return `CINV/${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,'0')}/${String(Date.now()).slice(-6)}`;}
router.get('/',async(req,res)=>{const q=String(req.query.q||'').trim();let sql=`SELECT ci.*,c.customer_code,s.code site_code,cl.name cluster_name FROM custom_invoices ci LEFT JOIN customers c ON c.id=ci.customer_id LEFT JOIN sites s ON s.id=c.site_id LEFT JOIN clusters cl ON cl.id=c.cluster_id WHERE 1=1`;const params=[];if(q){const like=`%${q}%`;sql+=` AND (ci.invoice_number LIKE ? OR ci.customer_name LIKE ? OR c.customer_code LIKE ? OR s.code LIKE ? OR cl.name LIKE ?)`;params.push(like,like,like,like,like);}sql+=` ORDER BY ci.id DESC`;const [rows]=await db.execute(sql,params);const [customers]=await db.query(`SELECT c.id,c.customer_code,c.name,s.code site_code,cl.name cluster_name FROM customers c JOIN sites s ON s.id=c.site_id LEFT JOIN clusters cl ON cl.id=c.cluster_id WHERE c.customer_status!='terminated' ORDER BY s.code,cl.name,c.name`);res.render('custom-invoices/index',{title:'Faktur Custom',invoices:rows,customers,q});});

router.get('/:id/pdf',async(req,res)=>{const [rows]=await db.execute(`SELECT ci.*,c.customer_code,s.code site_code,cl.name cluster_name FROM custom_invoices ci LEFT JOIN customers c ON c.id=ci.customer_id LEFT JOIN sites s ON s.id=c.site_id LEFT JOIN clusters cl ON cl.id=c.cluster_id WHERE ci.id=? LIMIT 1`,[req.params.id]);if(!rows.length)return res.status(404).send('Faktur custom tidak ditemukan.');const x=rows[0];createReportPdf(res,{title:`FAKTUR CUSTOM ${x.invoice_number}`,subtitle:`${x.customer_name||'-'}${x.customer_code?` · ${x.customer_code}`:''}${x.site_code?` · ${x.site_code} / Cluster ${x.cluster_name||'-'}`:''}`,filename:`faktur-custom-${String(x.invoice_number).replace(/[^A-Za-z0-9_-]/g,'-')}.pdf`,summaryItems:[{label:'TOTAL',value:rupiah(x.total),color:COLORS.purple},{label:'TANGGAL',value:date(x.invoice_date),color:COLORS.blue},{label:'JATUH TEMPO',value:date(x.due_date),color:COLORS.red},{label:'STATUS',value:String(x.status||'draft').toUpperCase(),color:x.status==='paid'?COLORS.green:COLORS.purple}],columns:[{label:'DESKRIPSI',width:4,value:()=>x.description||'Faktur custom INKAMNET'},{label:'NOMINAL',width:1.5,value:()=>rupiah(x.total),bold:true,align:'right'}],rows:[x],layout:'portrait',disposition:req.query.download==='0'?'inline':'attachment'});});

router.post('/',async(req,res)=>{const b=req.body;let customerName=b.customer_name||'';if(b.customer_id){const [c]=await db.execute(`SELECT name FROM customers WHERE id=?`,[b.customer_id]);if(c[0])customerName=c[0].name;}await db.execute(`INSERT INTO custom_invoices(invoice_number,customer_id,customer_name,invoice_date,due_date,description,total,status,created_by) VALUES(?,?,?,?,?,?,?,?,?)`,[invNo(),b.customer_id||null,customerName,b.invoice_date||new Date().toISOString().slice(0,10),b.due_date||null,b.description||null,b.total||0,b.status||'draft',req.session.user.id]);req.session.flash={type:'success',message:'Faktur custom dibuat.'};res.redirect('/custom-invoices');});
module.exports=router;
