const express=require('express');
const db=require('../config/db');
const router=express.Router();

router.get('/discounts',async(req,res)=>{const [discounts]=await db.query(`SELECT * FROM discounts ORDER BY is_active DESC,id DESC`);res.render('finance/discounts',{title:'Diskon',discounts});});
router.post('/discounts',async(req,res)=>{const b=req.body;await db.execute(`INSERT INTO discounts(name,type,amount,description,is_active) VALUES(?,?,?,?,1)`,[b.name,b.type||'flat',b.amount||0,b.description||null]);req.session.flash={type:'success',message:'Diskon ditambahkan.'};res.redirect('/discounts');});
router.post('/discounts/:id/toggle',async(req,res)=>{await db.execute(`UPDATE discounts SET is_active=IF(is_active=1,0,1) WHERE id=?`,[req.params.id]);res.redirect('/discounts');});

router.get('/charges',async(req,res)=>{const [charges]=await db.query(`SELECT * FROM additional_charges ORDER BY is_active DESC,id DESC`);res.render('finance/charges',{title:'Biaya Tambahan',charges});});
router.post('/charges',async(req,res)=>{const b=req.body;await db.execute(`INSERT INTO additional_charges(name,amount,description,is_active) VALUES(?,?,?,1)`,[b.name,b.amount||0,b.description||null]);req.session.flash={type:'success',message:'Biaya tambahan ditambahkan.'};res.redirect('/charges');});
router.post('/charges/:id/toggle',async(req,res)=>{await db.execute(`UPDATE additional_charges SET is_active=IF(is_active=1,0,1) WHERE id=?`,[req.params.id]);res.redirect('/charges');});

router.get('/cash/categories',async(req,res)=>{const [categories]=await db.query(`SELECT cc.*,s.code site_code FROM cash_categories cc LEFT JOIN sites s ON s.id=cc.site_id ORDER BY cc.type,cc.name`);const [sites]=await db.query(`SELECT id,code,name FROM sites WHERE is_active=1 ORDER BY code`);res.render('finance/cash-categories',{title:'Kategori Kas',categories,sites});});
router.post('/cash/categories',async(req,res)=>{const b=req.body;await db.execute(`INSERT INTO cash_categories(name,type,site_id,description,is_active) VALUES(?,?,?,?,1)`,[b.name,b.type,b.site_id||null,b.description||null]);req.session.flash={type:'success',message:'Kategori kas ditambahkan.'};res.redirect('/cash/categories');});

router.get('/cash',async(req,res)=>{const month=Number(req.query.month||new Date().getMonth()+1),year=Number(req.query.year||new Date().getFullYear()),site=req.query.site||'';let sql=`SELECT ct.*,cc.name category_name,cc.type category_type,s.code site_code FROM cash_transactions ct JOIN cash_categories cc ON cc.id=ct.category_id LEFT JOIN sites s ON s.id=ct.site_id WHERE MONTH(ct.transaction_date)=? AND YEAR(ct.transaction_date)=?`;const params=[month,year];if(site){sql+=` AND s.code=?`;params.push(site);}sql+=` ORDER BY ct.transaction_date DESC,ct.id DESC`;const [transactions]=await db.execute(sql,params);const [categories]=await db.query(`SELECT * FROM cash_categories WHERE is_active=1 ORDER BY type,name`);const [sites]=await db.query(`SELECT id,code,name FROM sites WHERE is_active=1 ORDER BY code`);const [[summary]]=await db.execute(`SELECT COALESCE(SUM(CASE WHEN cc.type='income' THEN ct.amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN cc.type='expense' THEN ct.amount ELSE 0 END),0) expense FROM cash_transactions ct JOIN cash_categories cc ON cc.id=ct.category_id LEFT JOIN sites s ON s.id=ct.site_id WHERE MONTH(ct.transaction_date)=? AND YEAR(ct.transaction_date)=?${site?` AND s.code=?`:''}`,[month,year,...(site?[site]:[])]);summary.balance=Number(summary.income)-Number(summary.expense);const [[collection]]=await db.execute(`SELECT COALESCE(SUM(CASE WHEN p.method='cash' AND p.status='confirmed' AND p.settlement_status='held_by_staff' THEN p.amount ELSE 0 END),0) cash_held,COUNT(CASE WHEN p.method='cash' AND p.status='confirmed' AND p.settlement_status='held_by_staff' THEN 1 END) held_count FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN customers c ON c.id=i.customer_id LEFT JOIN sites s ON s.id=c.site_id WHERE MONTH(p.paid_at)=? AND YEAR(p.paid_at)=?${site?` AND s.code=?`:''}`,[month,year,...(site?[site]:[])]);res.render('finance/cash',{title:'Arus Kas',transactions,categories,sites,summary,collection:collection||{},filters:{month,year,site}});});
router.post('/cash',async(req,res)=>{const b=req.body;await db.execute(`INSERT INTO cash_transactions(transaction_date,name,category_id,site_id,amount,notes,created_by) VALUES(?,?,?,?,?,?,?)`,[b.transaction_date,b.name,b.category_id,b.site_id||null,b.amount||0,b.notes||null,req.session.user.id]);req.session.flash={type:'success',message:'Transaksi kas dicatat.'};res.redirect('/cash');});
module.exports=router;
