const express=require('express');
const db=require('../config/db');
const { audit }=require('../services/auditService');
const router=express.Router();
function ticketCode(){const d=new Date();const p=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('');return `TT-${p}-${String(Date.now()).slice(-6)}`;}
async function technicalEmployees(){const [rows]=await db.query(`SELECT e.id,e.employee_code,e.name,e.user_id,p.name position_name,p.category FROM employees e LEFT JOIN positions p ON p.id=e.position_id WHERE e.is_active=1 AND (p.category IN ('technical','admin','management') OR p.category IS NULL) ORDER BY FIELD(p.category,'technical','admin','management'),e.name`);return rows;}

router.get('/',async(req,res)=>{
  const status=req.query.status||'',priority=req.query.priority||'',q=String(req.query.q||'').trim();
  let sql=`SELECT t.*,c.customer_code,c.name customer_name,s.code site_code,cl.name cluster_name,COALESCE(e.name,u.name) assigned_name,COALESCE(e.employee_code,'') assigned_code,(SELECT tu.progress_percent FROM ticket_updates tu WHERE tu.ticket_id=t.id ORDER BY tu.progress_date DESC,tu.id DESC LIMIT 1) progress_percent,(SELECT tu.progress_date FROM ticket_updates tu WHERE tu.ticket_id=t.id ORDER BY tu.progress_date DESC,tu.id DESC LIMIT 1) last_progress_date FROM tickets t LEFT JOIN customers c ON c.id=t.customer_id LEFT JOIN sites s ON s.id=c.site_id LEFT JOIN clusters cl ON cl.id=c.cluster_id LEFT JOIN employees e ON e.id=t.assigned_employee_id LEFT JOIN users u ON u.id=t.assigned_to WHERE 1=1`;
  const params=[];if(status){sql+=` AND t.status=?`;params.push(status);}if(priority){sql+=` AND t.priority=?`;params.push(priority);}if(q){const like=`%${q}%`;sql+=` AND (t.ticket_code LIKE ? OR t.subject LIKE ? OR c.name LIKE ? OR c.customer_code LIKE ? OR s.code LIKE ? OR cl.name LIKE ? OR COALESCE(e.name,u.name) LIKE ?)`;params.push(like,like,like,like,like,like,like);}sql+=` ORDER BY FIELD(t.status,'open','progress','pending','closed'), FIELD(t.priority,'critical','high','medium','low'), t.id DESC`;
  const [tickets]=await db.execute(sql,params);const [customers]=await db.query(`SELECT c.id,c.customer_code,c.name,s.code site_code,cl.name cluster_name FROM customers c JOIN sites s ON s.id=c.site_id LEFT JOIN clusters cl ON cl.id=c.cluster_id WHERE c.customer_status!='terminated' ORDER BY s.code,cl.name,c.name`);const employees=await technicalEmployees();const [[stats]]=await db.query(`SELECT SUM(status='open') open_count,SUM(status='progress') progress_count,SUM(status='pending') pending_count,SUM(status='closed') closed_count FROM tickets`);
  const [kpi]=await db.query(`SELECT e.id,e.name,e.employee_code,p.name position_name,COUNT(t.id) assigned_count,SUM(t.status='closed') closed_count,SUM(t.status IN ('open','progress','pending')) active_count,COALESCE((SELECT COUNT(*) FROM ticket_updates tu JOIN tickets tx ON tx.id=tu.ticket_id WHERE tx.assigned_employee_id=e.id AND tu.progress_date=CURDATE()),0) updates_today FROM employees e LEFT JOIN positions p ON p.id=e.position_id LEFT JOIN tickets t ON t.assigned_employee_id=e.id WHERE e.is_active=1 AND (p.category='technical' OR p.category IS NULL) GROUP BY e.id HAVING assigned_count>0 OR updates_today>0 ORDER BY closed_count DESC,assigned_count DESC,e.name`);
  kpi.forEach(x=>x.completion_rate=Number(x.assigned_count)>0?Math.round(Number(x.closed_count||0)/Number(x.assigned_count)*100):0);
  res.render('tickets/index',{title:'Ticketing',tickets,customers,employees,kpi,stats:stats||{},filters:{status,priority,q}});
});
router.post('/',async(req,res)=>{const b=req.body,code=ticketCode();let employee=null;if(b.assigned_employee_id){const [x]=await db.execute(`SELECT id,user_id FROM employees WHERE id=? AND is_active=1 LIMIT 1`,[b.assigned_employee_id]);employee=x[0]||null;}const [r]=await db.execute(`INSERT INTO tickets(ticket_code,customer_id,subject,type,priority,status,description,assigned_to,assigned_employee_id,opened_by,opened_at) VALUES(?,?,?,?,?,'open',?,?,?,?,NOW())`,[code,b.customer_id||null,b.subject,b.type||'Gangguan Internet',b.priority||'medium',b.description||null,employee?.user_id||null,employee?.id||null,req.session.user.id]);await audit({userId:req.session.user.id,action:'create',entityType:'ticket',entityId:r.insertId,description:`Buat tiket ${code}`,ip:req.ip});req.session.flash={type:'success',message:`Tiket ${code} berhasil dibuat.`};res.redirect(`/tickets/${r.insertId}`);});
router.post('/:id/status',async(req,res)=>{const status=req.body.status;await db.execute(`UPDATE tickets SET status=?,closed_at=IF(?='closed',NOW(),NULL) WHERE id=?`,[status,status,req.params.id]);req.session.flash={type:'success',message:'Status tiket diperbarui.'};res.redirect(req.body.return_to||'/tickets');});
router.post('/:id/assign',async(req,res)=>{let employee=null;if(req.body.assigned_employee_id){const [x]=await db.execute(`SELECT id,user_id FROM employees WHERE id=? AND is_active=1 LIMIT 1`,[req.body.assigned_employee_id]);employee=x[0]||null;}await db.execute(`UPDATE tickets SET assigned_employee_id=?,assigned_to=? WHERE id=?`,[employee?.id||null,employee?.user_id||null,req.params.id]);req.session.flash={type:'success',message:'PIC tiket diperbarui.'};res.redirect(`/tickets/${req.params.id}`);});
router.post('/:id/updates',async(req,res)=>{const percent=Math.max(0,Math.min(100,Number(req.body.progress_percent||0)));const allowed=new Set(['open','progress','pending','closed']);const status=allowed.has(req.body.status)?req.body.status:'progress';const note=String(req.body.note||'').trim();if(!note){req.session.flash={type:'danger',message:'Catatan progress wajib diisi.'};return res.redirect(`/tickets/${req.params.id}`);}await db.execute(`INSERT INTO ticket_updates(ticket_id,progress_date,progress_percent,status,note,updated_by) VALUES(?,?,?,?,?,?)`,[req.params.id,req.body.progress_date||new Date().toISOString().slice(0,10),percent,status,note,req.session.user.id]);await db.execute(`UPDATE tickets SET status=?,closed_at=IF(?='closed',COALESCE(closed_at,NOW()),NULL) WHERE id=?`,[status,status,req.params.id]);await audit({userId:req.session.user.id,action:'progress',entityType:'ticket',entityId:req.params.id,description:`Progress ${percent}% - ${status}`,ip:req.ip});req.session.flash={type:'success',message:'Progress harian tiket tersimpan.'};res.redirect(`/tickets/${req.params.id}`);});
router.get('/:id',async(req,res)=>{const [rows]=await db.execute(`SELECT t.*,c.customer_code,c.name customer_name,c.phone,c.address,s.code site_code,cl.name cluster_name,COALESCE(e.name,u.name) assigned_name,e.employee_code assigned_code,p.name assigned_position,op.name opened_by_name FROM tickets t LEFT JOIN customers c ON c.id=t.customer_id LEFT JOIN sites s ON s.id=c.site_id LEFT JOIN clusters cl ON cl.id=c.cluster_id LEFT JOIN employees e ON e.id=t.assigned_employee_id LEFT JOIN positions p ON p.id=e.position_id LEFT JOIN users u ON u.id=t.assigned_to LEFT JOIN users op ON op.id=t.opened_by WHERE t.id=? LIMIT 1`,[req.params.id]);if(!rows.length)return res.status(404).send('Ticket tidak ditemukan.');const [updates]=await db.execute(`SELECT tu.*,u.name updated_by_name FROM ticket_updates tu LEFT JOIN users u ON u.id=tu.updated_by WHERE tu.ticket_id=? ORDER BY tu.progress_date DESC,tu.id DESC`,[req.params.id]);const employees=await technicalEmployees();res.render('tickets/detail',{title:rows[0].ticket_code,ticket:rows[0],updates,employees});});
module.exports=router;
