const PDFDocument=require('pdfkit');
const path=require('path');
const fs=require('fs');
const COLORS={ink:'#121827',muted:'#6B7280',purple:'#603AEA',red:'#FF433E',green:'#18A979',line:'#E7E9F2',soft:'#F6F5FC',white:'#FFFFFF'};
function rupiah(v){return 'Rp '+new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(Number(v||0));}
function date(v){if(!v)return'-';try{return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Jakarta'}).format(new Date(v));}catch{return String(v);}}
function safe(v){return String(v??'-').replace(/[\u2013\u2014]/g,'-').replace(/\u2022/g,'-');}
function header(doc,title,subtitle){const logo=path.join(__dirname,'../public/img/inkamnet-wordmark-hq.png');doc.rect(0,0,doc.page.width,92).fill(COLORS.ink);if(fs.existsSync(logo))try{doc.image(logo,42,24,{fit:[125,44]});}catch{}doc.fillColor(COLORS.white).fontSize(17).font('Helvetica-Bold').text(title,205,28,{width:340,align:'right'});doc.fillColor('#B7BDCA').fontSize(8.5).font('Helvetica').text(subtitle,205,53,{width:340,align:'right'});doc.fillColor(COLORS.red).rect(42,91,doc.page.width-84,2).fill();doc.y=116;}
function footer(doc){const y=doc.page.height-42;doc.strokeColor(COLORS.line).moveTo(42,y-8).lineTo(doc.page.width-42,y-8).stroke();doc.fillColor(COLORS.muted).fontSize(7.5).text('PT INKAMNET NEXERA TECHNOLOGY',42,y,{width:260});doc.text(`Generated ${new Date().toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})}`,doc.page.width-300,y,{width:258,align:'right'});}
function summary(doc,items){const x=42,w=doc.page.width-84,gap=8,cols=Math.min(4,items.length),cw=(w-gap*(cols-1))/cols;let y=doc.y;items.forEach((it,i)=>{const xx=x+(i%cols)*(cw+gap);if(i>0&&i%cols===0)y+=61;doc.roundedRect(xx,y,cw,52,8).fillAndStroke(COLORS.soft,COLORS.line);doc.fillColor(COLORS.muted).fontSize(7).text(safe(it.label),xx+10,y+9,{width:cw-20});doc.fillColor(it.color||COLORS.ink).font('Helvetica-Bold').fontSize(11).text(safe(it.value),xx+10,y+25,{width:cw-20});doc.font('Helvetica');});doc.y=y+70;}
function table(doc,columns,rows){const x=42,total=doc.page.width-84;const widths=columns.map(c=>c.width);const sum=widths.reduce((a,b)=>a+b,0);const scaled=widths.map(v=>v/sum*total);const drawHead=()=>{let xx=x,y=doc.y;doc.fillColor(COLORS.ink).roundedRect(x,y,total,24,5).fill();columns.forEach((c,i)=>{doc.fillColor(COLORS.white).font('Helvetica-Bold').fontSize(7).text(c.label,xx+5,y+8,{width:scaled[i]-10,ellipsis:true});xx+=scaled[i];});doc.font('Helvetica');doc.y=y+26;};drawHead();
 rows.forEach((r,ri)=>{const vals=columns.map(c=>typeof c.value==='function'?c.value(r):r[c.key]);let heights=vals.map((v,i)=>doc.heightOfString(safe(v),{width:scaled[i]-10,fontSize:7}));let rh=Math.max(24,...heights.map(h=>h+10));if(doc.y+rh>doc.page.height-58){footer(doc);doc.addPage();header(doc,doc._reportTitle||'Laporan INKAMNET',doc._reportSubtitle||'');drawHead();}let xx=x,y=doc.y;if(ri%2===1)doc.fillColor('#FBFBFE').rect(x,y,total,rh).fill();doc.strokeColor(COLORS.line).moveTo(x,y+rh).lineTo(x+total,y+rh).stroke();columns.forEach((c,i)=>{doc.fillColor(c.color?c.color(r):COLORS.ink).font(c.bold?'Helvetica-Bold':'Helvetica').fontSize(7).text(safe(vals[i]),xx+5,y+7,{width:scaled[i]-10,ellipsis:false});xx+=scaled[i];});doc.font('Helvetica');doc.y=y+rh;});}
function createReportPdf(res,{title,subtitle,filename,summaryItems=[],columns=[],rows=[],disposition='attachment'}){const doc=new PDFDocument({size:'A4',margin:42,info:{Title:title,Author:'INKAMNET Control Center'}});doc._reportTitle=title;doc._reportSubtitle=subtitle;res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`${disposition==='inline'?'inline':'attachment'}; filename="${filename}"`);doc.pipe(res);header(doc,title,subtitle);if(summaryItems.length)summary(doc,summaryItems);table(doc,columns,rows);footer(doc);doc.end();}
module.exports={createReportPdf,rupiah,date,COLORS};
