const PDFDocument=require('pdfkit');
const path=require('path');
const fs=require('fs');

const COLORS={ink:'#0B1020',ink2:'#121A2C',muted:'#667085',muted2:'#98A2B3',purple:'#603AEA',purpleSoft:'#F1EDFF',red:'#FF433E',redSoft:'#FFF0EF',green:'#18A979',greenSoft:'#EAFBF5',blue:'#3478F6',line:'#E4E7EC',soft:'#F8F9FC',white:'#FFFFFF',black:'#101828'};
const COMPANY='PT INKAMNET NEXERA TECHNOLOGY';
const TAGLINE='From the Village, Online Everywhere';
function rupiah(v){return 'Rp '+new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(Number(v||0));}
function date(v){if(!v)return'-';try{return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Jakarta'}).format(new Date(v));}catch{return String(v);}}
function safe(v){return String(v??'-').replace(/[\u2013\u2014]/g,'-').replace(/\u2022/g,'-').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'');}
function nowText(){return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'}).format(new Date())+' WIB';}
function logoPath(){return path.join(__dirname,'../public/img/inkamnet-wordmark-hq.png');}
function drawLogo(doc,x,y,w=145,h=42){const logo=logoPath();if(fs.existsSync(logo)){try{doc.image(logo,x,y,{fit:[w,h],align:'left',valign:'center'});return;}catch{}}doc.fillColor(COLORS.white).font('Helvetica-Bold').fontSize(18).text('INKAMNET',x,y+8);}

function drawBrandHeader(doc,title,subtitle,compact=false){
  const width=doc.page.width,margin=doc.page.margins.left,usable=width-margin-doc.page.margins.right,h=compact?74:108;
  doc.save();doc.rect(0,0,width,h).fill(COLORS.ink);doc.rect(0,h-3,width*.72,3).fill(COLORS.purple);doc.rect(width*.72,h-3,width*.28,3).fill(COLORS.red);doc.circle(width-28,18,86).fillOpacity(.08).fill(COLORS.purple).fillOpacity(1);drawLogo(doc,margin,compact?17:25,145,42);
  const titleX=Math.max(margin+165,width*.41),titleW=width-margin-titleX;
  doc.fillColor('#A99BFF').font('Helvetica-Bold').fontSize(7.2).text(COMPANY,titleX,compact?14:20,{width:titleW,align:'right',characterSpacing:.55});
  doc.fillColor(COLORS.white).font('Helvetica-Bold').fontSize(compact?14:18).text(safe(title),titleX,compact?29:39,{width:titleW,align:'right'});
  if(!compact&&subtitle)doc.fillColor('#C8CEDA').font('Helvetica').fontSize(7.8).text(safe(subtitle),titleX,66,{width:titleW,align:'right',lineGap:2});doc.restore();doc.y=h+17;
  if(!compact){doc.save();doc.roundedRect(margin,doc.y,usable,34,7).fill(COLORS.soft);doc.fillColor(COLORS.muted).font('Helvetica-Bold').fontSize(6.8).text('DOKUMEN RESMI · INKAMNET CONTROL CENTER',margin+11,doc.y+11,{width:usable*.5});doc.fillColor(COLORS.muted).font('Helvetica').fontSize(6.8).text(`Dibuat: ${nowText()}`,margin+usable*.48,doc.y+11,{width:usable*.5,align:'right'});doc.restore();doc.y+=47;}
}
function drawSectionLabel(doc,label){const x=doc.page.margins.left;doc.fillColor(COLORS.purple).font('Helvetica-Bold').fontSize(7).text(safe(label).toUpperCase(),x,doc.y,{characterSpacing:.8});doc.y+=12;}
function drawSummary(doc,items){if(!items.length)return;drawSectionLabel(doc,'Ringkasan Eksekutif');const x=doc.page.margins.left,total=doc.page.width-doc.page.margins.left-doc.page.margins.right,cols=Math.min(4,Math.max(1,items.length)),gap=9,cw=(total-gap*(cols-1))/cols;let y=doc.y;items.forEach((it,i)=>{if(i>0&&i%cols===0)y+=63;const xx=x+(i%cols)*(cw+gap),accent=it.color||COLORS.purple;doc.save();doc.roundedRect(xx,y,cw,54,9).fillAndStroke(COLORS.white,COLORS.line);doc.roundedRect(xx,y,4,54,2).fill(accent);doc.fillColor(COLORS.muted).font('Helvetica-Bold').fontSize(6.5).text(safe(it.label),xx+13,y+10,{width:cw-22,characterSpacing:.3});doc.fillColor(accent).font('Helvetica-Bold').fontSize(10.8).text(safe(it.value),xx+13,y+28,{width:cw-22,ellipsis:true});doc.restore();});const rows=Math.ceil(items.length/cols);doc.y=y+54+18+(rows>1?(rows-1)*63:0);}
function valueFor(column,row){return typeof column.value==='function'?column.value(row):row[column.key];}function colorFor(column,row){return typeof column.color==='function'?column.color(row):(column.color||COLORS.black);}
function drawTable(doc,columns,rows,title,subtitle){drawSectionLabel(doc,'Detail Data');const x=doc.page.margins.left,total=doc.page.width-doc.page.margins.left-doc.page.margins.right,rawWidths=columns.map(c=>Number(c.width||1)),sum=rawWidths.reduce((a,b)=>a+b,0)||1,widths=rawWidths.map(v=>v/sum*total),headerH=29,bottomLimit=doc.page.height-doc.page.margins.bottom-31;
  function head(){const y=doc.y;doc.save();doc.roundedRect(x,y,total,headerH,7).fill(COLORS.ink2);let xx=x;columns.forEach((c,i)=>{doc.fillColor(COLORS.white).font('Helvetica-Bold').fontSize(6.7).text(safe(c.label).toUpperCase(),xx+6,y+9,{width:Math.max(10,widths[i]-12),align:c.align||'left',ellipsis:true});xx+=widths[i];});doc.restore();doc.y=y+headerH+2;}
  function nextPage(){doc.addPage();drawBrandHeader(doc,title,subtitle,true);head();}head();if(!rows.length){doc.save();doc.roundedRect(x,doc.y,total,48,7).fillAndStroke(COLORS.soft,COLORS.line);doc.fillColor(COLORS.muted).font('Helvetica').fontSize(8.5).text('Tidak ada data untuk filter yang dipilih.',x+12,doc.y+18,{width:total-24,align:'center'});doc.restore();doc.y+=58;return;}
  rows.forEach((row,ri)=>{const vals=columns.map(c=>safe(valueFor(c,row)));const heights=vals.map((v,i)=>doc.font(columns[i].bold?'Helvetica-Bold':'Helvetica').fontSize(7.05).heightOfString(v,{width:Math.max(20,widths[i]-12),lineGap:1}));let rh=Math.max(30,...heights.map(h=>h+14));rh=Math.min(rh,86);if(doc.y+rh>bottomLimit)nextPage();const y=doc.y;doc.save();if(ri%2===1)doc.rect(x,y,total,rh).fill('#FBFCFE');doc.strokeColor(COLORS.line).lineWidth(.6).moveTo(x,y+rh).lineTo(x+total,y+rh).stroke();let xx=x;columns.forEach((c,i)=>{doc.fillColor(colorFor(c,row)).font(c.bold?'Helvetica-Bold':'Helvetica').fontSize(7.05).text(vals[i],xx+6,y+8,{width:Math.max(20,widths[i]-12),height:rh-12,align:c.align||'left',ellipsis:true,lineGap:1});xx+=widths[i];});doc.restore();doc.y=y+rh;});
}
function drawReportSignoff(doc){const x=doc.page.margins.left,total=doc.page.width-doc.page.margins.left-doc.page.margins.right;if(doc.y+86>doc.page.height-doc.page.margins.bottom)doc.addPage();doc.y+=18;doc.save();doc.roundedRect(x,doc.y,total,64,8).fillAndStroke(COLORS.soft,COLORS.line);doc.fillColor(COLORS.black).font('Helvetica-Bold').fontSize(7.5).text('CATATAN DOKUMEN',x+13,doc.y+11);doc.fillColor(COLORS.muted).font('Helvetica').fontSize(7).text('Laporan ini dihasilkan secara elektronik dari INKAMNET Control Center berdasarkan data yang tersimpan pada saat dokumen dibuat.',x+13,doc.y+26,{width:total*.66,lineGap:2});doc.fillColor(COLORS.purple).font('Helvetica-Bold').fontSize(7).text(COMPANY,x+total*.70,doc.y+26,{width:total*.27,align:'right'});doc.fillColor(COLORS.muted).font('Helvetica').fontSize(6.5).text(TAGLINE,x+total*.70,doc.y+39,{width:total*.27,align:'right'});doc.restore();doc.y+=76;}
function drawFooterOnAllPages(doc,company=COMPANY){const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(range.start+i);const margin=doc.page.margins.left,y=doc.page.height-27,usable=doc.page.width-margin-doc.page.margins.right;doc.save();doc.strokeColor(COLORS.line).lineWidth(.7).moveTo(margin,y-8).lineTo(margin+usable,y-8).stroke();doc.fillColor(COLORS.muted).font('Helvetica').fontSize(6.7).text(safe(company),margin,y,{width:usable*.55});doc.text(`Halaman ${i+1} / ${range.count}`,margin+usable*.55,y,{width:usable*.45,align:'right'});doc.restore();}}
function createReportPdf(res,{title,subtitle,filename,summaryItems=[],columns=[],rows=[],disposition='attachment',layout=null}){const resolvedLayout=layout||((columns.length>=6)?'landscape':'portrait');const doc=new PDFDocument({size:'A4',layout:resolvedLayout,margins:{top:36,bottom:42,left:36,right:36},bufferPages:true,info:{Title:safe(title),Author:COMPANY,Subject:safe(subtitle||'')}});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`${disposition==='inline'?'inline':'attachment'}; filename="${String(filename).replace(/[\r\n"]/g,'-')}"`);doc.pipe(res);drawBrandHeader(doc,title,subtitle,false);drawSummary(doc,summaryItems);drawTable(doc,columns,rows,title,subtitle);drawReportSignoff(doc);drawFooterOnAllPages(doc);doc.end();}

function createCorporateInvoicePdf(res,{invoice,bank=null,payments=[],branding={},filename,disposition='inline'}){
  const x=invoice,company=branding.companyName||COMPANY,tagline=branding.tagline||TAGLINE,footer=branding.footer||'Dokumen digital resmi. Tidak memerlukan tanda tangan basah.';
  const companyDetails=[branding.address,branding.phone?`Tel. ${branding.phone}`:null,branding.email,branding.website,branding.taxId?`NPWP/ID Pajak: ${branding.taxId}`:null].filter(Boolean).join(' · ');
  const doc=new PDFDocument({size:'A4',margins:{top:38,bottom:42,left:42,right:42},bufferPages:true,info:{Title:`Invoice ${safe(x.invoice_number)}`,Author:safe(company)}});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`${disposition==='attachment'?'attachment':'inline'}; filename="${String(filename).replace(/[\r\n"]/g,'-')}"`);doc.pipe(res);
  const W=doc.page.width,L=42,R=42,U=W-L-R;doc.save();doc.rect(0,0,W,122).fill(COLORS.ink);doc.rect(0,119,W*.74,3).fill(COLORS.purple);doc.rect(W*.74,119,W*.26,3).fill(COLORS.red);if(branding.logoFilePath&&fs.existsSync(branding.logoFilePath)){try{doc.image(branding.logoFilePath,L,28,{fit:[150,45],align:'left',valign:'center'});}catch{drawLogo(doc,L,28,150,45);}}else drawLogo(doc,L,28,150,45);doc.fillColor(COLORS.white).font('Helvetica-Bold').fontSize(25).text('INVOICE',W-230,22,{width:188,align:'right'});doc.fillColor('#A99BFF').font('Helvetica-Bold').fontSize(8).text(safe(x.invoice_number),W-260,54,{width:218,align:'right'});doc.fillColor('#C8CEDA').font('Helvetica').fontSize(7.3).text(safe(company),W-300,73,{width:258,align:'right'});const contact=[branding.phone,branding.email].filter(Boolean).join(' · ');if(contact)doc.fontSize(6.2).text(safe(contact),W-320,91,{width:278,align:'right'});doc.restore();
  let y=146;doc.fillColor(COLORS.muted).font('Helvetica-Bold').fontSize(6.5).text('DITAGIHKAN KEPADA',L,y,{characterSpacing:.8});doc.fillColor(COLORS.black).font('Helvetica-Bold').fontSize(13).text(safe(x.customer_name),L,y+15,{width:U*.52});doc.fillColor(COLORS.muted).font('Helvetica').fontSize(8).text(`${safe(x.customer_code)}\n${safe(x.address||'-')}\n${safe(x.phone||'-')}`,L,y+35,{width:U*.52,lineGap:3});
  const bx=L+U*.58,bw=U*.42;doc.save();doc.roundedRect(bx,y,bw,86,9).fillAndStroke(COLORS.soft,COLORS.line);const meta=[['Tanggal Invoice',date(x.invoice_date)],['Jatuh Tempo',date(x.due_date)],['Periode',`${String(x.period_month).padStart(2,'0')}/${x.period_year}`],['Site / Cluster',`${safe(x.site_code)} / ${safe(x.cluster_name||'-')}`]];meta.forEach((m,i)=>{doc.fillColor(COLORS.muted).font('Helvetica').fontSize(6.5).text(m[0],bx+12,y+11+i*18,{width:bw*.45});doc.fillColor(COLORS.black).font('Helvetica-Bold').fontSize(7).text(m[1],bx+bw*.46,y+11+i*18,{width:bw*.48,align:'right'});});doc.restore();
  y+=111;doc.fillColor(COLORS.purple).font('Helvetica-Bold').fontSize(7).text('RINCIAN LAYANAN',L,y,{characterSpacing:.8});y+=14;doc.save();doc.roundedRect(L,y,U,30,7).fill(COLORS.ink2);const cols=[L+12,L+U*.61,L+U*.72,L+U*.98];doc.fillColor(COLORS.white).font('Helvetica-Bold').fontSize(6.7).text('DESKRIPSI',cols[0],y+10,{width:U*.52});doc.text('QTY',cols[1],y+10,{width:U*.08,align:'center'});doc.text('HARGA',cols[2],y+10,{width:U*.24,align:'right'});doc.restore();y+=32;
  const rowH=54;doc.save();doc.rect(L,y,U,rowH).fillAndStroke(COLORS.white,COLORS.line);doc.fillColor(COLORS.black).font('Helvetica-Bold').fontSize(8.5).text(`${safe(x.package_name)}${x.is_prorata?' (Prorata)':''}`,L+12,y+10,{width:U*.52});doc.fillColor(COLORS.muted).font('Helvetica').fontSize(6.8).text(`Layanan Internet INKAMNET · ${safe(x.site_code)} · Cluster ${safe(x.cluster_name||'-')}`,L+12,y+27,{width:U*.52});doc.fillColor(COLORS.black).font('Helvetica').fontSize(8).text('1',cols[1],y+17,{width:U*.08,align:'center'});doc.font('Helvetica-Bold').text(rupiah(x.subtotal),L+U*.72,y+17,{width:U*.25,align:'right'});doc.restore();y+=72;
  const leftW=U*.51,rightX=L+U*.57,rightW=U*.43;doc.save();doc.roundedRect(L,y,leftW,106,9).fillAndStroke(COLORS.soft,COLORS.line);doc.fillColor(COLORS.black).font('Helvetica-Bold').fontSize(7.5).text('INFORMASI PEMBAYARAN',L+13,y+13);if(bank){doc.fillColor(COLORS.purple).font('Helvetica-Bold').fontSize(11).text(safe(bank.bank_name),L+13,y+34);doc.fillColor(COLORS.black).font('Helvetica-Bold').fontSize(10).text(safe(bank.account_number),L+13,y+51);doc.fillColor(COLORS.muted).font('Helvetica').fontSize(7).text(`a.n. ${safe(bank.account_name)}`,L+13,y+68,{width:leftW-26});}else doc.fillColor(COLORS.muted).font('Helvetica').fontSize(7.5).text('Hubungi admin INKAMNET untuk informasi rekening pembayaran.',L+13,y+38,{width:leftW-26});doc.fillColor(COLORS.muted).font('Helvetica').fontSize(6.3).text('Cantumkan nomor invoice pada referensi pembayaran.',L+13,y+88,{width:leftW-26});doc.restore();
  const totals=[['Subtotal',rupiah(x.subtotal)],['Diskon',`- ${rupiah(x.discount)}`],['Total Invoice',rupiah(x.total)],['Terbayar',rupiah(x.paid_amount)],['SISA TAGIHAN',rupiah(x.outstanding)]];doc.save();doc.roundedRect(rightX,y,rightW,146,9).fillAndStroke(COLORS.white,COLORS.line);totals.forEach((t,i)=>{const yy=y+14+i*25;const last=i===totals.length-1;if(i===2||last){doc.strokeColor(COLORS.line).lineWidth(.6).moveTo(rightX+12,yy-6).lineTo(rightX+rightW-12,yy-6).stroke();}doc.fillColor(last?COLORS.black:COLORS.muted).font(last?'Helvetica-Bold':'Helvetica').fontSize(last?8:7).text(t[0],rightX+13,yy,{width:rightW*.44});doc.fillColor(last?(Number(x.outstanding)>0?COLORS.red:COLORS.green):COLORS.black).font('Helvetica-Bold').fontSize(last?12:8).text(t[1],rightX+rightW*.43,yy-1,{width:rightW*.51,align:'right'});});doc.restore();
  y+=164;const status=String(x.status||'').toUpperCase();doc.save();const sc=status==='PAID'?COLORS.green:(status==='OVERDUE'?COLORS.red:COLORS.purple),sf=status==='PAID'?COLORS.greenSoft:(status==='OVERDUE'?COLORS.redSoft:COLORS.purpleSoft);doc.roundedRect(L,y,112,25,12).fill(sf);doc.fillColor(sc).font('Helvetica-Bold').fontSize(7).text(`STATUS · ${status}`,L+10,y+9,{width:92,align:'center'});doc.restore();
  if(payments.length){y+=42;doc.fillColor(COLORS.purple).font('Helvetica-Bold').fontSize(7).text('RIWAYAT PEMBAYARAN',L,y,{characterSpacing:.8});y+=14;payments.slice(0,5).forEach((p,i)=>{doc.fillColor(COLORS.black).font('Helvetica-Bold').fontSize(7).text(rupiah(p.amount),L,y+i*17,{width:110});doc.fillColor(COLORS.muted).font('Helvetica').fontSize(6.6).text(`${safe(p.method).toUpperCase()} · ${safe(p.status).toUpperCase()} · ${date(p.paid_at)}`,L+116,y+i*17,{width:U-116});});}
  const footerY=doc.page.height-91;doc.save();doc.strokeColor(COLORS.line).moveTo(L,footerY).lineTo(L+U,footerY).stroke();doc.fillColor(COLORS.black).font('Helvetica-Bold').fontSize(7).text(safe(company),L,footerY+12,{width:U*.55});doc.fillColor(COLORS.muted).font('Helvetica').fontSize(5.8).text(safe(companyDetails||footer),L,footerY+25,{width:U*.59,lineGap:1.5});doc.fillColor(COLORS.purple).font('Helvetica-Bold').fontSize(6.5).text(safe(tagline),L+U*.62,footerY+18,{width:U*.38,align:'right'});doc.fillColor(COLORS.muted).font('Helvetica').fontSize(5.8).text(safe(footer),L+U*.62,footerY+32,{width:U*.38,align:'right',lineGap:1.5});doc.restore();drawFooterOnAllPages(doc,company);doc.end();
}
module.exports={createReportPdf,createCorporateInvoicePdf,rupiah,date,COLORS};
